sudo: required
language: node_js
node_js:
  - 6.4.0
before_script:
  - npm install --only=dev
  - npm install karma-jasmine
  - npm install -g karma jasmine bower
  - bower install
script:
  - karma start --single-run