sudo: required
language: node_js
node_js:
  - 6.4.0
before_script:
  - npm install -g karma karma-jasmine jasmine jasmine-core phantomjs karma-phantomjs-launcher bower
  - bower install
script:
  - karma start --single-run --browsers PhantomJS_custom